/*
 * ComboBoxFileChooser.java
 *
 * Created on July 20, 2004, 5:06 PM
 */

package com.cosylab.vdct.util;
import javax.swing.JFileChooser;

/**
 *
 * @author  ilist
 */
public class ComboBoxFileChooser extends javax.swing.JDialog {
    
    private int returnValue = JFileChooser.ERROR_OPTION;
    
    /** Creates new form ComboBoxFileChooser */
    public ComboBoxFileChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //getRootPane().setDefaultButton(jButtonDefault);
		//getRootPane().setWindowDecorationStyle(JRootPane.FILE_CHOOSER_DIALOG);
		//final File blankFile = new File(""); 
		//jFileChooser.setSelectedFile(blankFile);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        jFileChooser = new javax.swing.JFileChooser();
        jCheckBoxAbsoluteDBD = new javax.swing.JCheckBox();
        jButtonDefault = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jFileChooser.setControlButtonsAreShown(false);
        jFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooserActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jFileChooser, gridBagConstraints);

        jCheckBoxAbsoluteDBD.setText("Use absolute DBD paths");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 7, 10, 0);
        getContentPane().add(jCheckBoxAbsoluteDBD, gridBagConstraints);

        jButtonDefault.setText("Save");
        jButtonDefault.setMinimumSize(new java.awt.Dimension(75, 25));
        jButtonDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDefaultActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 11, 5);
        getContentPane().add(jButtonDefault, gridBagConstraints);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 11);
        getContentPane().add(jButtonCancel, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
		returnValue = JFileChooser.CANCEL_OPTION;
		jFileChooser.cancelSelection();
		setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
		returnValue = JFileChooser.CANCEL_OPTION;
		jFileChooser.cancelSelection();
		setVisible(false);
		//jFileChooser.getActionMap().get("cancelSelection").actionPerformed(evt);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDefaultActionPerformed     
		if (jFileChooser.getActionMap().get("approveSelection")!=null) {
			jFileChooser.getActionMap().get("approveSelection").actionPerformed(evt);
			setVisible(false);	
		} else {
			if (jFileChooser.getSelectedFile()!=null) {
				returnValue = JFileChooser.APPROVE_OPTION;
				jFileChooser.approveSelection();
				setVisible(false);
			}
		}
    }//GEN-LAST:event_jButtonDefaultActionPerformed

    private void jFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserActionPerformed
    }//GEN-LAST:event_jFileChooserActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ComboBoxFileChooser(new javax.swing.JFrame(), true).show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDefault;
    private javax.swing.JCheckBox jCheckBoxAbsoluteDBD;
    private javax.swing.JFileChooser jFileChooser;
    // End of variables declaration//GEN-END:variables
    
	/**
	 * @return
	 */
	public javax.swing.JCheckBox getJCheckBoxAbsoluteDBD() {
		return jCheckBoxAbsoluteDBD;
	}

	/**
	 * @return
	 */
	public javax.swing.JFileChooser getJFileChooser() {
		return jFileChooser;
	}

	public int showDialog() {	
		returnValue = JFileChooser.ERROR_OPTION;
		setLocationRelativeTo(getParent());		
		show();
		return returnValue;
	}

}
